// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// fast_PMS_cpp
Rcpp::List fast_PMS_cpp(arma::mat& x, arma::vec& y, double theta);
RcppExport SEXP _PMS_fast_PMS_cpp(SEXP xSEXP, SEXP ySEXP, SEXP thetaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type theta(thetaSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_PMS_cpp(x, y, theta));
    return rcpp_result_gen;
END_RCPP
}
// fast_data_gen
Rcpp::List fast_data_gen(int n, int p, double R2, arma::vec& beta_nonzero);
RcppExport SEXP _PMS_fast_data_gen(SEXP nSEXP, SEXP pSEXP, SEXP R2SEXP, SEXP beta_nonzeroSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< double >::type R2(R2SEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type beta_nonzero(beta_nonzeroSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_data_gen(n, p, R2, beta_nonzero));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_PMS_fast_PMS_cpp", (DL_FUNC) &_PMS_fast_PMS_cpp, 3},
    {"_PMS_fast_data_gen", (DL_FUNC) &_PMS_fast_data_gen, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_PMS(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
