# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#'@importFrom Rcpp evalCpp
#'@useDynLib PMS, .registration=TRUE
NULL

#'Fast posterior mean screening without prior knowledge
#'@param x: n x p covariate matrix
#'@param y: n x 1 response vector
#'@param theta: positive number control the prior precision. Default value is 1e-3.
#'@return a list of two variables,
#'\describe{
#' \item{pms_select}{indices of the predictors from most important to least important}
#' \item{pms_stat}{a p by 1 vector of posterior mean statistics}
#'}
#'@author Jian Kang \email{<jiankang@@umich.edu>}
#'@export
fast_PMS_cpp <- function(x, y, theta = 1e-3) {
    .Call(`_PMS_fast_PMS_cpp`, x, y, theta)
}

#'Simulate data from linear regression model
#'@param n an integer represents the sample size.
#'@param p an integer which is the dimension of covariates.
#'@param R2 a number between 0 and 1 to indicate the signal to noise ratio.
#'@param beta_nonzero a vector of q (q > 0) non-zero coefficients for the first q covariates.
#'@return a list of four variables
#'\describe{
#'  \item{x}{an n by p matrix, n observations of p-dimensional covariates}
#'  \item{y}{an n by 1 vector, n observations of response variable}
#'  \item{sigma2}{a positive number for noise variance}
#'  \item{beta_nonzero}{the true non-zero regression coefficients for the first q covariates}
#'}
#'@author Jian Kang \email{<jiankang@@umich.edu>}
#'@examples
#'dat <- fast_data_gen(1000,10000,0.9,c(1,2,3))
#'@export
fast_data_gen <- function(n, p, R2, beta_nonzero) {
    .Call(`_PMS_fast_data_gen`, n, p, R2, beta_nonzero)
}

#'Posterior mean variable screening based on local spatial smoothing
#'
#'@param x a design matrix of dimension n by p, where n is the sample size and p
#'is the number of spatially varying predictors
#'@param y a vector of length n for response variable
#'@param coords a matrix of dimension p by d (d>0) for the spatial locations,
#'where d is the dimension of space
#'@param neighbors a matrix of dimension p by q (q>0) for indices of neighbors
#'@param num_neighbors a vector of length p for the number of
#'neighbors for each predictor
#'@param rho: a vector of length p for spatial smoothness parameters
#'@param theta: positive number control the prior precision. Default value is 1e-3.
#'@return a list of two variables,
#'\describe{
#' \item{pms_select}{indices of the predictors from most important to least important}
#' \item{pms_stat}{a p by 1 vector of posterior mean statistics}
#'}
#'@author Jian Kang \email{<jiankang@@umich.edu>}
#'@examples
#' maskfile <- file.path(system.file("nifti", package="PMS"),"MNI-maxprob-thr0-2mm.nii.gz")
#' mask <- oro.nifti::readNIfTI(maskfile)
#' imgfiles <- file.path(system.file("nifti", package="PMS"),sprintf("VBM_example_0%d.nii.gz",1:5))
#' img_dat <- fast_read_imgs_mask(imgfiles,maskfile)
#' img1 <- oro.nifti::readNIfTI(imgfiles[1])
#' nb <- find_brain_image_neighbors(img1, mask, radius=1)
#' # simulate data
#' n = 200
#' p = ncol(img_dat)
#' x = matrix(rnorm(n*p),nrow=n,ncol=p)
#' beta_coef = rep(0,length=ncol(img_dat))
#' true_idx = nb$mask_img_nb[249,]
#' beta_coef[true_idx] = 1
#' rho = rep(0.01,length=ncol(img_dat))
#' y = x%*%beta_coef + rnorm(nrow(img_dat),sd=0.1)
#' res <- fast_PMS_local_spatial(x=x, y = y, coords=nb$maskcoords,neighbors=nb$mask_img_nb,num_neighbors=nb$num_neighbors, rho = rho)
#'@export
fast_PMS_local_spatial <- function(x, y, coords, neighbors, num_neighbors, rho, theta = 1e-3) {
    .Call(`_PMS_fast_PMS_local_spatial`, x, y, coords, neighbors, num_neighbors, rho, theta)
}

#'Fast Read multiple imaging data files on a brain mask
#'@param imgfiles a character vector of imaging file names
#'@param maskfile a character scalar for the  mask file
#'@param verbose a positive integer showing the progress on the number of images being loaded
#'@return a matrix of dimension n by p, where n is the number of images and p is the number of voxels on the mask
#'@author Jian Kang \email{<jiankang@@umich.edu>}
#'@examples
#' maskfile <- file.path(system.file("nifti", package="PMS"),"MNI-maxprob-thr0-2mm.nii.gz")
#' mask <- oro.nifti::readNIfTI(maskfile)
#' imgfiles <- file.path(system.file("nifti", package="PMS"),sprintf("VBM_example_0%d.nii.gz",1:5))
#' img_dat <- fast_read_imgs_mask(imgfiles,maskfile)
#'@export
fast_read_imgs_mask <- function(imgfiles, maskfile, verbose = 100L) {
    .Call(`_PMS_fast_read_imgs_mask`, imgfiles, maskfile, verbose)
}

