# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#'@importFrom Rcpp evalCpp
#'@useDynLib PMS, .registration=TRUE
NULL

#'@export
fast_PMS_cpp <- function(x, y, theta = 1e-3) {
    .Call(`_PMS_fast_PMS_cpp`, x, y, theta)
}

#'@export
fast_data_gen <- function(n, p, R2, beta_nonzero) {
    .Call(`_PMS_fast_data_gen`, n, p, R2, beta_nonzero)
}

